Repository CloudNationHQ/terraform-azure-vnet, pull requests merged in 2024-10, with the labels that each got.

#90 fix: fix vnet dependency order for proper destruction
  locals.tf
  main.tf
Labels: bug

#92 feat!: aligned route table properties
  README.md
  examples/complete/main.tf
  examples/default/main.tf
  examples/delegations/main.tf
  examples/nsg-rules/main.tf
  examples/routes/main.tf
  examples/service-endpoints/main.tf
  main.tf
Labels: enhancement

#94 feat: auto generated docs and refine makefile
  Makefile
  README.md
  modules/vhub-connection/README.md
  tests/deploy_test.go
Labels: documentation

#96 feat!: corrected vnet output and made several improvements
  README.md
  examples/complete/README.md
  examples/complete/main.tf
  examples/complete/naming.tf
  examples/complete/outputs.tf
  examples/complete/rules.tf
  examples/default/README.md
  examples/default/main.tf
  examples/delegations/README.md
  examples/delegations/main.tf
  examples/nsg-rules/README.md
  examples/nsg-rules/main.tf
  examples/nsg-rules/naming.tf
  examples/routes/README.md
  examples/routes/main.tf
  examples/routes/naming.tf
  examples/service-endpoints/README.md
  examples/service-endpoints/main.tf
  examples/vhub-connection/main.tf
  main.tf
  outputs.tf
  variables.tf
Labels: bug, enhancement

#98 fix: remove parlalellism limitation from tests
  tests/deploy_test.go
Labels: bug

#100 fix: resolve type mismatch in nsg name coalesce
  main.tf
Labels: bug
